### PR TITLE
Search country

### PR DESCRIPTION
**Pull request by elenamarinaki**
Hi Adriana,

In this branch I have implemented the country search functionality. A brief description about how this user story works:
1. the page loads
2. the user is presented with the seach `input` and the Global Stats (not implemented yet, the values are hard-coded)
3. the user enters a country in the  search field
4. the results appear right below, through a new template
5. the user enters another country in the search field
6. the new results appear in the same template (we don't create and attach in the DOM a new one for every search)

I have a couple of things I want to improve, like how to present more accurate results, since not all countries have their data arranged in the same way in the API. It takes some tweaking in some cases like the UK or USA for example. 

Since the most basic functionality is working though, I am sending it for you to review it, so we can add it to the main branch.

Many thanks :)

### CODE REVIEW

**Review by aaadriana — APPROVED** [review]
👍 looks perfect to me. 
Thank you, Elena

**Comment by aaadriana** [comment]
Hey Elena,
So what's the plan with the button search? 
We need to add the date too, do you have any plans for this?  or should I look at this?

**Comment by elenamarinaki** [comment]
Hi Adriana,

I did not have a button search, because I was focusing on mobile first and usually in searches on mobile we are just using the return button. Would it be better to add one anyway?

Yes, it would be cool to add a date for the global stats. Or you mean the date as a search option?

**Comment by aaadriana** [comment]
Hi Elena, 
Yes, sorry, that's true about mobile, we can add a button just for the pc version. 

Now I am playing with your code, to try to remember and to understand better Asynchronous. 
I tried to make just one function for the fetch, and not to hard code the  error message, something like this: 

```
const getJSON = function (url, errorMsg = "Something went wrong") {
  return fetch(url)
    .then((response) => {
      if (!response.ok) throw new Error(`${errorMsg}: (${response.status})`);
      return response.json();
    })
    .then((array) => {
      if (array.length !== 0) {
        return array[array.length - 1];
      } else throw new Error(`${errorMsg}`);
    });
};
```
and to call the function like this 
```
getJSON(
      `https://api.covid19api.com/live/country/${data}`,
      "Error in retrieving country data!"
    )
```

But I don't have the results I want. I don't receive the correct status (ex: 440, 400).
I'll try again later, after we finish our project, or if you want to have a look..

About the date, maybe we can add a new line in our template?  Like this, we can show the results are in real-time? 
And I think it's better if you add the code, like this, we avoid conflicts in our code. What do you think? 

          `<li>
            <div class="row global-stats">
              <p>Date:</p>
              <p id="date"></p>
            </div>
           </li>`
       `document.querySelector("#date").textContent = countryData.Date;
        domFragment.querySelector("#date").textContent = countryData.Date;`

Now I will start my tasks, I hope I will have something nice this weekend. 🥰  

Thank you, Elena, your code is super easy to read 💓

**Comment by elenamarinaki** [comment]
Oh happy it makes some sense :)

I think it's a good idea to have the date as you said. If you don't mind, feel free to add it. 

Just a clarification though: this date is about the global stats or not? So, there's an issue (or maybe most probably I haven't found a better way to do it) with the `GET Live by Country - All Status`. When we pick a country, it bring results in an array from different dates that go back to 2 months ago. The last element in this array is the most recent date (hence the `return array[array.length - 1]` in the code). This way we can avoid having to specify the most recent time through comparison of dates. But, for the global stats we need to display the date, I mean we need to have the date somewhere anyways.

About the `error`: if I understand correctly, you mean having a separate function that is handling the errors, right? So the function you have above would be called inside the `searchCountry` function instead of `.catch`, correct? That's a good idea actually! How would we pass the arguments though in it? In the code above though, you need a `.catch` somewhere to catch the error, because now it's just rejecting your promise. The last step after all the `.then`s should be a `.catch`.

Please let me know if I understood correctly, thanks for checking everything out ❤️ can't wait to see what goods you're "baking"! 🥰

**Comment by aaadriana** [comment]
Hey, 
I will restore the branch because I managed to refactor the code. 
My mistake was that I closed the beach, sorry Elena. 
Have a look and let me know what do you think. 
I tried not to repeat the code too much.

**Comment by elenamarinaki** [comment]
Where shall I look Adriana, have you sent a pull request?

**Comment by aaadriana** [comment]
Yes, you can find the new pull request

**Comment by elenamarinaki** [comment]
Thanks for sending this Adriana!

It's perfect, the code is more re-usable this way for sure. 👏 👏 Thanks for taking the time to work around this :) 

I am merging with the main 😄

**Pull request merged**
